name: fltld
description: A Flutter Lightning Network Wallet App
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  intl: ">=0.14.0"
  share : ^0.6.0

  # grpc
  grpc: ^2.8.0
  protobuf: ^1.1.0

  #bitcoin
  bech32: any
  dart_lnurl:
    path: packages/dart_lnurl

  #qrcode
  barcode_scan: ^1.0.0 ## obsolete
  qr_flutter: ^3.0.1

  #ui
  flutter_speed_dial: ^1.2.1
  keyboard_actions: ^2.1.2

  #settings
  flutter_secure_storage: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: LndAppIcons
      fonts:
        - asset: fonts/LndAppIcons.ttf
  assets:
    - images/party-popper.png
