/// Flutter icons LndAppIcons
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  LndAppIcons
///      fonts:
///       - asset: fonts/LndAppIcons.ttf
///
///
/// * Font Awesome, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class LndAppIcons {
  LndAppIcons._();

  static const _kFontFam = 'LndAppIcons';

  static const IconData qrcode = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData flash_1 = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData doc_text =
      const IconData(0xf0f6, fontFamily: _kFontFam);
  static const IconData bitcoin = const IconData(0xf15a, fontFamily: _kFontFam);
}
